/* 

1) MEMBER_ID 컬럼에 PRIMARY KEY 제약조건 설정.

2) MEMBER_PWD 컬럼에 NOT NULL 제약조건 설정.

3) MEMBER_NAME 컬럼에 가변 길이 문자열 30byte 설정.

*/

-- MEMBERS 테이블 생성

CREATE TABLE MEMBERS(

MEMBER_ID VARCHAR2(20) PRIMARY KEY,

MEMBER_PWD VARCHAR2(20) NOT NULL,

MEMBER_NAME VARCHAR(30),

MEMBER_AGE NUMBER,

MEMBER_EMAIL VARCHAR2(50),


);



-- BOARDS 테이블 생성

CREATE TABLE BOARDS(

BOARD_NO NUMBER PRIMARY KEY,

BOARD_TITLE VARCHAR2(100),

BOARD_CONTENT VARCHAR2(4000),

BOARD_WRITER VARCHAR2(20) 
CONSTRAINT MEMBERS_ID
REFERENCES MEMBERS (MEMBER_ID),

BOARD_REG_DATE DATE DEFAULT CURRENT_DATE
);

-- 모든 User 조회
SELECT
		USER_NO,
		USER_ID,
		USER_PW,
		USER_NAME,
		TO_CHAR(ENROLL_DATE,'YYYY"년"MM"월"DD"일"')
		ENROLL_DATE
		
FROM TB_USER
ORDER BY USER_NO ASC;
-- 검색어가 이름에 포함된 User 조회
SELECT
		USER_NO,
		USER_ID,
		USER_PW,
		USER_NAME,
		TO_CHAR(ENROLL_DATE,'YYYY"년"MM"월"DD"일"')
		ENROLL_DATE
		
FROM TB_USER
WHERE USER_NAME LIKE '%'||'?'||'%'
ORDER BY USER_NO ASC;

-- USER_NO를 입력 받아 일치하는 User 삭제(DELETE)
DELETE
FROM TB_USER
WHERE USER_NO != 1;
-- 일치하는 USER_NO가 있을 경우 : 1행 삭제
-- 일치하는 USER_NO가 없을 경우 : 0행 삭제
COMMIT;
ROLLBACK;

-- ID,PW가 일치하는 회원의 USER_NO(PK) 조회
SELECT USER_NO
FROM TB_USER
WHERE USER_ID = 'user03'
AND 	USER_PW = 'pass03';

-- USER_NO(PK)가 일치하는 회원의 이름 수정

UPDATE TB_USER
SET USER_NAME = '이순신 장군'
WHERE USER_NO = '8';

-- 중복되는 아이디가 있는지 조회
-- 중복이면 1, 아니면 0
SELECT COUNT(*)
FROM TB_USER
WHERE USER_ID = 'user02';

SELECT *
FROM TB_USER
ORDER BY 1 ASC;

SELECT *
FROM TB_USER
WHERE USER_NO = TO_NUMBER('24');

SELECT *
FROM TB_USER;

